# Name: Gnanitha Suryadevara
# Course: SWE 645 - HW2
# Purpose: Nginx configuration for serving the static web application

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Serve custom error page for 404
    error_page 404 /error.html;
    location = /error.html {
        internal;
    }
}
